default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: pompeya
  password: pompeya
  host: localhost
  port: 5432

development:
  <<: *default
  database: pompeya_development

test:
  <<: *default
  database: pompeya_test
